export const SNEAKER_LIST_REQUEST = "SNEAKER_LIST_REQUEST";
export const SNEAKER_LIST_SUCCESS = "SNEAKER_LIST_SUCCESS";
export const SNEAKER_LIST_FAIL = "SNEAKER_LIST_FAIL";

export const SNEAKER_DETAILS_REQUEST = "SNEAKER_DETAILS_REQUEST";
export const SNEAKER_DETAILS_SUCCESS = "SNEAKER_DETAILS_SUCCESS";
export const SNEAKER_DETAILS_FAIL = "SNEAKER_DETAILS_FAIL";

export const SNEAKER_DELETE_REQUEST = "SNEAKER_DELETE_REQUEST";
export const SNEAKER_DELETE_SUCCESS = "SNEAKER_DELETE_SUCCESS";
export const SNEAKER_DELETE_FAIL = "SNEAKER_DELETE_FAIL";

export const SNEAKER_CREATE_REQUEST = "SNEAKER_CREATE_REQUEST";
export const SNEAKER_CREATE_SUCCESS = "SNEAKER_CREATE_SUCCESS";
export const SNEAKER_CREATE_FAIL = "SNEAKER_CREATE_FAIL";
export const SNEAKER_CREATE_RESET = "SNEAKER_CREATE_RESET";

export const SNEAKER_UPDATE_REQUEST = "SNEAKER_UPDATE_REQUEST";
export const SNEAKER_UPDATE_SUCCESS = "SNEAKER_UPDATE_SUCCESS";
export const SNEAKER_UPDATE_FAIL = "SNEAKER_UPDATE_FAIL";
export const SNEAKER_UPDATE_RESET = "SNEAKER_UPDATE_RESET";

export const SNEAKER_CREATE_REVIEW_REQUEST = "SNEAKER_CREATE_REVIEW_REQUEST";
export const SNEAKER_CREATE_REVIEW_SUCCESS = "SNEAKER_CREATE_REVIEW_SUCCESS";
export const SNEAKER_CREATE_REVIEW_FAIL = "SNEAKER_CREATE_REVIEW_FAIL";
export const SNEAKER_CREATE_REVIEW_RESET = "SNEAKER_CREATE_REVIEW_RESET";

export const SNEAKER_TOP_REQUEST = "SNEAKER_TOP_REQUEST";
export const SNEAKER_TOP_SUCCESS = "SNEAKER_TOP_SUCCESS";
export const SNEAKER_TOP_FAIL = "SNEAKER_TOP_FAIL";
